# Generated by Django 5.2.7 on 2025-10-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='barangay',
            index=models.Index(fields=['city'], name='locations_b_city_id_b76148_idx'),
        ),
        migrations.AddIndex(
            model_name='citymunicipality',
            index=models.Index(fields=['province'], name='locations_c_provinc_e2b76f_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['region'], name='locations_p_region__4bbd95_idx'),
        ),
    ]
