# Generated by Django 5.2 on 2025-10-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0053_alter_servicerepairaccreditationapplication_fax_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='mobile_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='tax_identification_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
