# Generated by Django 5.2.5 on 2025-10-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0053_alter_servicerepairaccreditationapplication_fax_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespromotionpermitapplication',
            name='checklist_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='salespromotionpermitapplication',
            name='inspection_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='salespromotionpermitapplication',
            name='opp_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='checklist_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='inspection_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='opp_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
