# Generated by Django 5.2 on 2025-10-16 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0054_alter_servicerepairaccreditationapplication_mobile_number_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.barangay'),
        ),
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='city_or_municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.citymunicipality'),
        ),
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.province'),
        ),
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region'),
        ),
    ]
