# Generated by Django 5.2.5 on 2025-10-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0054_salespromotionpermitapplication_checklist_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerepairaccreditationapplication',
            name='checklist_status',
        ),
        migrations.RemoveField(
            model_name='servicerepairaccreditationapplication',
            name='inspection_status',
        ),
        migrations.RemoveField(
            model_name='servicerepairaccreditationapplication',
            name='opp_status',
        ),
    ]
