# Generated by Django 5.2.5 on 2025-10-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0055_remove_servicerepairaccreditationapplication_checklist_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='checklist_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='inspection_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='opp_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
