# Generated by Django 5.2.7 on 2025-10-18 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0055_alter_servicerepairaccreditationapplication_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistevaluationsheet',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inspectionvalidationreport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderofpayment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personaldatasheet',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salespromotionpermitapplication',
            name='date_filed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servicerepairaccreditationapplication',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
