# Generated by Django 5.2.7 on 2025-10-18 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0056_alter_checklistevaluationsheet_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderofpayment',
            name='sales_promotion_permit_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_of_payment', to='documents.salespromotionpermitapplication'),
        ),
    ]
