# Generated by Django 5.2.5 on 2025-10-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0056_servicerepairaccreditationapplication_checklist_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespromotionpermitapplication',
            name='checklist_status',
        ),
        migrations.RemoveField(
            model_name='salespromotionpermitapplication',
            name='inspection_status',
        ),
        migrations.RemoveField(
            model_name='salespromotionpermitapplication',
            name='opp_status',
        ),
        migrations.RemoveField(
            model_name='servicerepairaccreditationapplication',
            name='checklist_status',
        ),
        migrations.RemoveField(
            model_name='servicerepairaccreditationapplication',
            name='inspection_status',
        ),
        migrations.RemoveField(
            model_name='servicerepairaccreditationapplication',
            name='opp_status',
        ),
        migrations.AddField(
            model_name='salespromotionpermitapplication',
            name='checklist_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salespromotionpermitapplication',
            name='inspection_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salespromotionpermitapplication',
            name='opp_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='checklist_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='inspection_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerepairaccreditationapplication',
            name='opp_done',
            field=models.BooleanField(default=False),
        ),
    ]
