# Generated by Django 5.2.8 on 2025-11-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0085_remove_otherbusinessnamerelatedformmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionreport',
            name='rc_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
