# Generated by Django 5.2.8 on 2025-11-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0086_collectionreport_rc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionreport',
            name='responsibility_center_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
